# пример конфигурационного файла
# обязательно вставить токен сообщества в token, иначе деды не запустятся
# файл переименовать в configuration.toml

[Kiberded]
token = ''  # токен для вк
timetable = ['08:00', '09:50', '11:40', '13:40', '15:30', '17:20', '19:05', '20:50']  # начала пар
group_token = 201485931  # id группы в вк
num_of_base = 589999  # объем базы анекдотов
path = '/root/kiberded/'  # путь к директории с репозиторием, обязательно добавить / в конце!
cron_time = '06:00' # время ежедневного крона
tables_time = "19:00"  # Расписание в ЛС
is_sendCron = 1  # флаг отправки крона
is_sendToast = 1  # флаг отправки тостов
token_telegram = ''  # токен для телеграма
token_telegram_backup = ''  # токен бэкапного деда
deeplink_token_key = ''  # часть ключа для авторизации пользователя из ВК в ТГ
telegram_admin_chat = -1001668185586  # chat.id админского чата в тг (для отладки, отправки ошибок и все такое)
telegram_backup_chat = -640134320  # chat.id чата для бэкапов
telegram_books_chat = -1001596534310 # chat.id чата для книжек
telegram_dayofdaypics_chat = -1001758218447 # chat.id чата с картиночками дня дня
vk_ded_page_login = ""  # "Длюдеда" - страница-пользователь для Кибердеда
vk_ded_page_password = ""
web_secret = ''  # ключ для генерации токенов в веб-админке
enable_acme_challenge = 0  # флаг монтирования директории /.well-known для получения ssl-сертификата через certbot

